# Lucas's Bash RC
# Version 2026-03-14

if [[ $- != *i* ]] ; then
	return
fi

# Add local bin folder to PATH for distros that dont do this automagically
export PATH="$HOME/.local/bin:$PATH"

# -- Shell Environment --
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# -- Stuff I stole from Debian --
HISTSIZE=1000
HISTFILESIZE=2000

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'

# No duplicates or lines starting with spaces in history
HISTCONTROL=ignoreboth
# Append rather than overwrite history
shopt -s histappend
# Use ** to match a files and directories
shopt -s globstar

# -- Aliases --
alias ff='clear && fastfetch'
alias l='ls -lA'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias rm='rm -vi'
alias mv='mv -vi'
alias cp='cp -vi'

# -- Prompt --
eval "$(starship init bash)"
